backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "acasa"
    label: "Pagina Acasă"
    file: "dist/index.html"
    fields:
      - {label: "Titlu principal", name: "title", widget: "string"}
      - {label: "Descriere scurtă", name: "description", widget: "text"}

  - name: "despre"
    label: "Despre Noi"
    file: "dist/despre.html"
    fields:
      - {label: "Text principal", name: "body", widget: "markdown"}
