backend:
  name: github
  repo: Mihail-2025/virtualbiz
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pagini"
    label: "Pagini"
    files:
      - label: "Pagina Principală"
        name: "acasa"
        file: "index.html"
        fields:
          - { label: "Titlu", name: "title", widget: "string" }
          - { label: "Conținut", name: "body", widget: "markdown" }
