backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "articole"
    label: "Articole"
    folder: "content/articole"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titlu", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Conținut", name: "body", widget: "markdown" }
